# fly.toml app configuration file generated for weather-info on 2025-02-02T01:52:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weather-info'
primary_region = 'arn'

[build]
  [build.env]
    VITE_SOME_KEY = "792ab0d7399d1353d93a24ab21f10894" # Set your API key here

[env]
  PORT = "3000" # Port for the backend server

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
